version: "3.7"

services:
  app:
    image: hostmonitor/app
    container_name: app
    build: .
    restart: always
    env_file: .env
    environment:
      - SSH_ADDRESS=${SSH_ADDRESS}
      - SSH_USER=${SSH_USER}
      - SSH_PASSWORD=${SSH_PASSWORD}
    ports:
      - 8080:8080
  swagger-ui:
    image: swaggerapi/swagger-ui
    container_name: swagger-ui
    volumes:
      - ./internal/infrastructure/grpc:/foo
    environment:
      - SWAGGER_JSON=/foo/api.swagger.json
    ports:
      - 8090:8080