version: "3.7"

services:
  app:
    image: ghcr.io/goalt/hostmonitor:$IMAGE_VERSION
    container_name: hostmonitor
    restart: always
    ports: ["20005:8080"]
    environment:
      - SSH_ADDRESS=${DEPLOY_SSH_ADDRESS}
      - SSH_USER=${DEPLOY_SSH_USER}
      - SSH_PASSWORD=${DEPLOY_SSH_PASSWORD}
  js:
    image: ghcr.io/goalt/hostmonitor-js:1.0.5
    container_name: hostmonitor-js
    restart: always
    ports: ["20004:80"]