version: "3.7"

services:
  app:
    depends_on: [ db ]
    image: ghcr.io/goalt/hostmonitor:$IMAGE_VERSION
    container_name: hostmonitor
    ports: [ "20003:8080" ]
    restart: always
    volumes: [ fs_data:/data ]
    environment:
      - SSH_ADDRESS=${SSH_ADDRESS}
      - SSH_USER=${SSH_USER}
      - SSH_PASSWORD=${SSH_PASSWORD}